
package proyectomatematicas;

import java.io.IOException;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author juan1
 */
public class numeros extends javax.swing.JFrame { 
    /**
     * Creates new form numeros
     */
    
    public  Clip clip;
    public String ruta="/sonido/";
    
 
    
    public numeros() {
        initComponents();
          setLocationRelativeTo(null);
    }
    
    public void sonido(String archivo){
        try {
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta+archivo+".wav")));
            clip.start();
            
        }catch(LineUnavailableException | UnsupportedAudioFileException | IOException e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(990, 720));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\1n.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 58, 71);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\2n.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 120, 58, 86);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\3n.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 210, 55, 67);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\4n.png")); // NOI18N
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 320, 61, 64);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\5n.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 430, 59, 64);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\6n.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 30, 52, 65);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\7n.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 110, 61, 69);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\8n.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 200, 66, 63);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\9n.png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 300, 72, 62);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\10n.png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 420, 102, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(200, 60, 28, 24);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(200, 240, 28, 24);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(200, 150, 28, 24);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(200, 340, 28, 24);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(590, 50, 28, 24);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 440, 28, 24);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(590, 130, 28, 24);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(600, 320, 28, 24);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(590, 220, 28, 24);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(600, 440, 28, 24);

        jButton1.setText("Uno");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 50, 65, 42);

        jButton2.setText("Dos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 130, 65, 42);

        jButton3.setText("Tres");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 240, 67, 41);

        jButton4.setText("Cuatro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 340, 65, 43);

        jButton5.setText("Cinco");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(290, 430, 65, 43);

        jButton6.setText("Seis");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(710, 40, 63, 42);

        jButton7.setText("Siete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(710, 130, 63, 42);

        jButton8.setText("Ocho");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(710, 210, 63, 43);

        jButton9.setText("Nueve");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(710, 320, 63, 42);

        jButton10.setText("Diez");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(710, 430, 63, 42);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Atras");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(40, 580, 40, 14);

        jButton11.setBackground(new java.awt.Color(255, 255, 153));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\sigi.png")); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(20, 570, 110, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      sonido("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       numeros1 ingreso = new numeros1();
                    ingreso.setVisible(true);
                    ingreso.pack();  
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    sonido("1");       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sonido("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
sonido("3");      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     sonido("4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     sonido("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        sonido("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        sonido("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      sonido("9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      sonido("10");
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
