/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomatematicas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author juan1
 */
public class resta extends javax.swing.JFrame {

    /**
     * Creates new form resta
     */
    public resta() {
        initComponents();
         setLocationRelativeTo(null);
          cronometro.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiempo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(990, 720));
        getContentPane().setLayout(null);

        tiempo.setText("0:0");
        getContentPane().add(tiempo);
        tiempo.setBounds(40, 310, 40, 14);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 100, 130, 140);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 100, 140, 140);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 110, 140, 120);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 410, 70, 110);

        jLabel6.setRequestFocusEnabled(false);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 400, 140, 110);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 400, 130, 110);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(600, 410, 80, 90);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 140)); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 390, 80, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan1\\Downloads\\tablero1.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(972, 750));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, -280, 1080, 980);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 540, 70, 120);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 540, 70, 120);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 540, 70, 120);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton4.setText("0");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 540, 70, 120);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(410, 540, 70, 120);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(510, 540, 70, 120);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(710, 540, 70, 120);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(810, 540, 70, 120);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton9.setText("6");
        jButton9.setToolTipText("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(610, 540, 70, 120);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jButton10.setText("9");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(900, 540, 70, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //  jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("1");
        // validar((JButton) evt.getSource());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //   jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //  jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("0");
        // validar((JButton) evt.getSource());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("4");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("5");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //  jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //   jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("6");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //  jLabel9.setFont(new java.awt.Font("Tahoma", 0, 46));
        jLabel9.setText("9");
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    Thread cronometro = new Thread(){
    public void run (){
        int horas=0,min=0,seg=0;
        for(;;){
            try{
                seg++;
                 if (seg>59){
                    seg=0;
                    min++;
                     }
                 
                 if(seg>=2){
                    jLabel3.setIcon(new ImageIcon("C:\\Users\\juan1\\Downloads\\naranja1.png"));  
                 jLabel4.setIcon(new ImageIcon("C:\\Users\\juan1\\Downloads\\naranja1.png")); 
                 jLabel5.setIcon(new ImageIcon("C:\\Users\\juan1\\Downloads\\naranja1.png")); 
                 }
                 if(seg>=0){
                     jLabel2.setIcon(new ImageIcon("C:\\Users\\juan1\\Downloads\\2su1.png")); 
                     jLabel6.setIcon(new ImageIcon("C:\\Users\\juan1\\Downloads\\suma1.png")); 
                     jLabel7.setIcon(new ImageIcon("C:\\Users\\juan1\\Downloads\\1su1.png")); 
                     jLabel8.setIcon(new ImageIcon("C:\\Users\\juan1\\Downloads\\igual1.png")); 
                 }
                 if(min>59){
                     seg=0;
                     min=0;
                     
                 }
                 
                 if(seg==10){
                     if(jLabel9.getText().equals("1")){
                         JOptionPane.showMessageDialog(null, "Bien Hecho", "Felicitaciones", JOptionPane.INFORMATION_MESSAGE);
                     }else{
                         JOptionPane.showMessageDialog(null, "Sigue repasando", "Esta vez no", JOptionPane.ERROR_MESSAGE);
                     }
                     
                      }
                 
                 
                 
                 
                 tiempo.setText(min + ":" + seg);
                 Thread.sleep(999);
            }catch (InterruptedException e){
                
            }
        }  }

        
    }; 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
